version = 1

test_patterns = [
  "**/*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/1set/gut"

[[analyzers]]
name = "test-coverage"
enabled = true
