name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 4
      matrix:
        vm-os: [ubuntu-latest, macOS-latest]
        go-version: [1.12.10, 1.13.1]

    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 2

    - name: Get dependencies
      shell: bash
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      shell: bash
      run: ./build.sh ci

    - name: Upload report to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.codecov_token}}
        file: ./coverage.txt
