name: macOS
on:
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 21 * * 0"

jobs:
  build:
    name: Build on macOS
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        vm-os: [macOS-latest]
        go-version: [1.11.13, 1.12.17, 1.13.9, 1.14.1]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          fetch-depth: 2

      - name: Get dependencies
        shell: bash
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build & Test
        shell: bash
        run: script/build.sh ci

      - name: Notify me via IFTTT if it fails on ${{ matrix.vm-os }}
        if: failure() && endsWith(github.ref, '/master')
        uses: cixo/ifttt-trigger@v0.3
        with:
          key: ${{ secrets.ifttt_maker_key }}
          event: github_1set_build
          value1: ${{ github.repository }} for ${{ matrix.vm-os }}
          value2: ${{ github.event_name }}
          value3: ${{ job.status }}
