name: Windows
on:
  push:
    paths-ignore:
    - '**.md'
  schedule:
    - cron:  '0 21 * * 5'

jobs:

  build:
    name: Build on Windows
    runs-on: ${{ matrix.vm-os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        vm-os: [windows-latest]
        go-version: [1.11.13, 1.12.13, 1.13.4]

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 2

    - name: Get dependencies
      shell: bash
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build & Test
      shell: bash
      run: ./build.sh ci
